In [46]:
print("github")

github

In [47]:
import pandas as pd
import numpy as np

In [52]:
df=pd.read_csv("/Users/natsutosisumita/Downloads/Pokemon.csv")

In [53]:
(df[df["type1"] == "Normal"])

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
24,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
25,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
26,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
27,18,Mega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
28,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,780,Drampa,Normal,Dragon,485,78,60,85,135,91,36,7,False
965,819,Skwovet,Normal,NaN,275,70,55,55,35,35,25,8,False
966,820,Greedent,Normal,NaN,460,120,95,95,55,75,20,8,False
979,831,Wooloo,Normal,NaN,270,42,40,55,40,45,48,8,False
980,832,Dubwool,Normal,NaN,490,72,80,100,60,90,88,8,False

In [69]:
df["sum"]=df["hp"]+df["attack"]+df["defense"]+df["sp_attack"]+df["sp_defense"]+df["speed"]
df

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary,sum
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,3,Gigantamax Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,896,Glastrier,Ice,NaN,580,100,145,130,65,110,30,8,True,580
1068,897,Spectrier,Ghost,NaN,580,100,65,60,145,80,130,8,True,580
1069,898,Calyrex,Psychic,Grass,500,100,80,80,80,80,80,8,True,500
1070,898,Ice Rider Calyrex,Psychic,Ice,680,100,165,150,85,130,50,8,True,680
1071,898,Shadow Rider Calyrex,Psychic,Ghost,680,100,85,80,165,100,150,8,True,680

In [80]:
df_600=(df[df["sum"]==600])

In [102]:
df_600nl=(df_600[(df_600["legendary"]==False) & (~df_600["name"].str.contains("Mega"))])
df_600nl

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary,sum
202,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False,600
310,248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False,600
453,373,Salamence,Dragon,Flying,600,95,135,80,110,80,100,3,False,600
457,376,Metagross,Steel,Psychic,600,80,135,130,95,90,70,3,False,600
538,445,Garchomp,Dragon,Ground,600,108,130,95,80,85,102,4,False,600
747,635,Hydreigon,Dark,Dragon,600,92,105,90,125,90,98,5,False,600
828,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False,600
923,784,Kommo-o,Dragon,Fighting,600,75,110,125,100,105,85,7,False,600
1051,887,Dragapult,Dragon,Ghost,600,88,120,75,100,75,142,8,False,600