In [10]:
print("github")

github

In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("/Users/natsutosisumita/Downloads/Pokemon.csv")

In [13]:
df.head()

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,3,Gigantamax Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [21]:
(df[df["type1"] == "Normal"])

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
24,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
25,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
26,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
27,18,Mega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
28,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,780,Drampa,Normal,Dragon,485,78,60,85,135,91,36,7,False
965,819,Skwovet,Normal,NaN,275,70,55,55,35,35,25,8,False
966,820,Greedent,Normal,NaN,460,120,95,95,55,75,20,8,False
979,831,Wooloo,Normal,NaN,270,42,40,55,40,45,48,8,False
980,832,Dubwool,Normal,NaN,490,72,80,100,60,90,88,8,False